// @audio/effect — audio effects umbrella re-exporting every @audio/effect-* atom.
// For smaller bundles, depend directly on the individual atom.
// Dynamics processors live in @audio/dynamics; spatial tools in @audio/spatial; pitch shifting in @audio/shift.

export { default as phaser } from '@audio/effect-phaser'
export { default as flanger } from '@audio/effect-flanger'
export { default as chorus } from '@audio/effect-chorus'
export { default as wah } from '@audio/effect-wah'
export { default as tremolo } from '@audio/effect-tremolo'
export { default as vibrato } from '@audio/effect-vibrato'
export { default as rotary } from '@audio/effect-rotary'
export { default as ringMod } from '@audio/effect-ringmod'
export { default as frequencyShifter } from '@audio/effect-freqshift'
export { default as autoWah } from '@audio/effect-autowah'
export { default as delay } from '@audio/effect-delay'
export { default as multitap } from '@audio/effect-multitap'
export { default as pingPong } from '@audio/effect-pingpong'
export { default as distortion } from '@audio/effect-distortion'
export { default as bitcrusher } from '@audio/effect-bitcrusher'
export { default as exciter } from '@audio/effect-exciter'
export { default as slewLimiter } from '@audio/effect-slew'
export { default as noiseShaping } from '@audio/effect-noiseshaper'
export { default as gain } from '@audio/effect-gain'
export { default as mixer } from '@audio/effect-mixer'
export { default as grainDelay } from '@audio/effect-graindelay'
export { default as lofi } from '@audio/effect-lofi'
export { default as sbr } from '@audio/effect-sbr'
export { default as stutter } from '@audio/effect-stutter'
export { default as subbass } from '@audio/effect-subbass'
export { default as tapeStop } from '@audio/effect-tapestop'
